title: Nauts
tagline: The data center automation experts!
description: "Nauts are experts in Datacenter Automation. We are experienced infrastructure engineers with a focus on containerization."
url: http://staging.nauts.io
email: info@nauts.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333
  blue: 00b3fe

permalink: pretty
markdown: kramdown
kramdown:
    input: GFM

gems:
  - jekyll-redirect-from
